// TODO: Убрать отсюда импорт и заменить поломанные импорты
export { Button } from '../button'
export { Title } from '../title'
export { Divider } from '../divider'
export { Error } from '../error'
export { Loading } from '../loading'
export { Logo } from '../logo'
export { SkeletonShape } from '../skeleton-shape'
export { Message } from '../message'
export { Image } from '../image'
export { AnimatedCheck } from '../animated-check'
export { ContextMenu } from '../context-menu'
export { TextArea } from '../textarea'
export { default as Input } from './input'
export { default as SubmitButton } from './submit-button'
export { default as SwitchToggleWrapper } from './switch-toggle-wrapper'
export { default as Wrapper } from './wrapper'
export { default as LinkButton } from './link-button'
export { default as LoadFileButton } from './load-file-button'
export { default as FormBlock } from './form-block'
export { default as FileLink } from './file-link'
export { default as TeacherWidthModal } from './teacher-with-modal'
