// TODO: Убрать отсюда импорт и заменить поломанные импорты
export { Button } from '../button'
export { Title } from '../title'
export { Divider } from '../divider'
export { Error } from '../error'
export { Loading } from '../loading'
export { Logo } from '../logo'
export { SkeletonShape } from '../skeleton-shape'
export { Message } from '../message'
export { Image } from '../image'
export { AnimatedCheck } from '../animated-check'
export { TextArea } from '../textarea'
export { default as SubmitButton } from '../submit-button'
export { default as Input } from '../input'
export { SwitchToggleWrapper } from './switch-toggle-wrapper'
export { default as Wrapper } from './wrapper'
export { LinkButton } from './link-button'
export { FormBlock } from './form-block'
export { HrBlock } from './hr-block'
export { FileLink } from './file-link'
export { default as TeacherWithModal } from './teacher-with-modal'
export { CenterPage } from './center-page'
