export enum ApplicationFormCodes {
    USG_GETHOSTEL_OOZ = 'usg_gethostel_ooz',
    USG_GETHOSTEL_Z = 'usg_gethostel_z',
    USG_GETHOSTEL_AO = 'usg_gethostel_ao',
    USG_GETHOSTEL_BENEFIT = 'usg_gethostel_benefit',
    USG_GETHOSTEL_FAMILY = 'usg_gethostel_family',
    USG_CONTR_TERMINATION = 'usg_contr_termination',
    USG_RELOCATION_INNER = 'usg_relocation_inner',
    USG_RELOCATION = 'usg_relocation',
    OBUCH = 'obuch',
    STATUS_SOBES = 'status_sobes',
    SPRVIZOV = 'sprvizov',
    PERS_DATA = 'pers_data',
    PROPUSK_RESTORE = 'propusk_restore',
    PASSPORT_DATA = 'passport_data',
    DIPL_OTL = 'dipl_otl',
    STATUS_REGULAR = 'status_regular',
    OKID_LICAKKRED = 'okid_licakkred',
    MILDOCS = 'mildocs',
    VOEN_UCH = 'voen_uch',
    PR_DONATE = 'pr_donate',
    PR_MATPOM = 'pr_matpom',
    PR_SOCSTIP = 'pr_socstip',
    HIGH_SCHOLARSHIP = 'high_scholarship',
    DOP_SOGL = 'dop_sogl',
    SEND_PAYMENT_EDU = 'send_payment_edu',
    FREE_REQUEST = 'free_request',
}
