export enum ApplicationFormCodes {
    USG_GETHOSTEL_O = 'usg_gethostel_o', // Предоставление права проживания (очная форма)
    USG_GETHOSTEL_OOZ = 'usg_gethostel_ooz', // Предоставление права проживания (очно-заочная форма)
    USG_GETHOSTEL_Z = 'usg_gethostel_z', // Предоставление права проживания (заочная форма)
    USG_GETHOSTEL_AO = 'usg_gethostel_ao', // Предоставление права проживания в период академического отпуска
    USG_GETHOSTEL_BENEFIT = 'usg_gethostel_benefit', // Предоставление права льготного проживания
    USG_GETHOSTEL_FAMILY = 'usg_gethostel_family', // Предоставление права проживания в семейной комнате
    USG_CONTR_TERMINATION = 'usg_contr_termination', // Расторжение договора найма
    USG_RELOCATION_INNER = 'usg_relocation_inner', // Переселение внутри общежития
    USG_RELOCATION = 'usg_relocation', // Переселение в другое общежитие
    ACCOMMODATION_FOR_GRADUATES = 'accommodation_for_graduates', // Предоставление права проживания в период каникул
    OBUCH = 'obuch',
    STATUS_SOBES = 'status_sobes',
    SPRVIZOV = 'sprvizov',
    PERS_DATA = 'pers_data',
    PROPUSK_RESTORE = 'propusk_restore',
    PASSPORT_DATA = 'passport_data',
    DIPL_OTL = 'dipl_otl',
    STATUS_REGULAR = 'status_regular',
    OKID_LICAKKRED = 'okid_licakkred',
    MILDOCS = 'mildocs',
    MIL_REG = 'mil_reg',
    VOEN_UCH = 'voen_uch',
    PR_DONATE = 'pr_donate',
    PR_MATPOM = 'pr_matpom',
    PR_SOCSTIP = 'pr_socstip',
    HIGH_SCHOLARSHIP = 'high_scholarship',
    DOP_SOGL = 'dop_sogl',
    SEND_PAYMENT_EDU = 'send_payment_edu',
    FREE_REQUEST = 'free_request',
    CRS_VACATIONS = 'crs_vacations',
    CRS_ACADEMVAC = 'crs_academvac',
    CRS_EXPULSION = 'crs_expulsion',
    CRS_ATTESTAT = 'crs_attestat',
    MEDICAL_CERT = 'postRequestMedicalCertificate',
    STUD_EMPLOYMENT = 'stud_employment',
    WORK_TRANSFER = '',
    EXTRA_HOLIDAY_COLL = '',
    HOLIDAY_PLANNING = '',
    HOLIDAY_WORK = '',
    DISMISSAL = '',
    HOLIDAY_POSTPONED = '',
    PART_TIME_EMPLOYMENT = '',
}

export enum ApplicationTeachersFormCodes {
    CONTACT_INFO_ACTUALIZATION = 'contact-info-actualization',
    DATA_VERIFICATION_ROUTE = 'data-verification',
    ISSUANCE_OF_LICENSES = 'issuance-of-licenses',
    GETTING_COMPUTER_EQUIPMENT = 'getting-computer-equipment',
    CONNECTING_COMPUTER = 'connecting-computer',
    PRINTER_MAINTENANCE = 'printer-maintenance',
    QUESTION_SED = 'question-sed',
    QUESTION_PERSONAL_ACCOUNT = 'question-personal-account',
    OTHER_IT_SERVICES = 'other-it-services',
    CERTIFICATE_FROM_PLACE_OF_WORK = 'certificate-from-the-place-of-work',
    VISA_CERTIFICATE = 'visa-certificate',
    CERTIFICATE_OF_WORK_EXPERIENCE = 'certificate-of-work-experience',
    NUMBER_OF_UNUSED_VACATION_DAYS = 'number-of-unused-vacation-days',
    COPY_OF_EMPLOYMENT_RECORD = 'copy-of-the-employment-record',
    COPIES_OF_DOCUMENTS_FROM_PERSONAL_FILE = 'copies-of-documents-from-the-personal-file',
    WORK_ON_TERMS_OF_EXTERNAL_CONCURRENCY = 'work-on-the-terms-of-external-concurrency',
    CERTIFICATE_TIME_PARENTAL_LEAVE = 'certificate-time-parental-leave',
    COURIER = 'courier',
    PERSONA_INCOME_TAX_REFERENCE = 'persona-income-tax-reference',
    PAYMENT_OF_CHILD_BIRTH_ALLOWANCE = 'payment-of-child-birth-allowance',
    PAYMENT_FOR_CHILD_CARE = 'payment-for-child-care',
}
