export enum ApplicationFormCodes {
    USG_GETHOSTEL_O = 'usg_gethostel_o', // Предоставление права проживания (очная форма)
    USG_GETHOSTEL_OOZ = 'usg_gethostel_ooz', // Предоставление права проживания (очно-заочная форма)
    USG_GETHOSTEL_Z = 'usg_gethostel_z', // Предоставление права проживания (заочная форма)
    USG_GETHOSTEL_AO = 'usg_gethostel_ao', // Предоставление права проживания в период академического отпуска
    USG_GETHOSTEL_BENEFIT = 'usg_gethostel_benefit', // Предоставление права льготного проживания
    USG_GETHOSTEL_FAMILY = 'usg_gethostel_family', // Предоставление права проживания в семейной комнате
    USG_CONTR_TERMINATION = 'usg_contr_termination', // Расторжение договора найма
    USG_RELOCATION_INNER = 'usg_relocation_inner', // Переселение внутри общежития
    USG_RELOCATION = 'usg_relocation', // Переселение в другое общежитие
    OBUCH = 'obuch',
    STATUS_SOBES = 'status_sobes',
    SPRVIZOV = 'sprvizov',
    PERS_DATA = 'pers_data',
    PROPUSK_RESTORE = 'propusk_restore',
    PASSPORT_DATA = 'passport_data',
    DIPL_OTL = 'dipl_otl',
    STATUS_REGULAR = 'status_regular',
    OKID_LICAKKRED = 'okid_licakkred',
    MILDOCS = 'mildocs',
    VOEN_UCH = 'voen_uch',
    PR_DONATE = 'pr_donate',
    PR_MATPOM = 'pr_matpom',
    PR_SOCSTIP = 'pr_socstip',
    HIGH_SCHOLARSHIP = 'high_scholarship',
    DOP_SOGL = 'dop_sogl',
    SEND_PAYMENT_EDU = 'send_payment_edu',
    FREE_REQUEST = 'free_request',
    CRS_VACATIONS = 'crs_vacations',
    CRS_ACADEMVAC = 'crs_academvac',
    CRS_EXPULSION = 'crs_expulsion',
    CRS_ATTESTAT = 'crs_attestat',
    WORK_TRANSFER = '',
    EXTRA_HOLIDAY_COLL = '',
    HOLIDAY_PLANNING = '',
    HOLIDAY_WORK = '',
    DISMISSAL = '',
    HOLIDAY_POSTPONED = '',
    PART_TIME_EMPLOYMENT = '',
}
