export const MOCK_DELETE = {
    id: 123409,
    user_status: 'stud',
    status: 'Окончил (выпущен)',
    course: '4',
    name: 'Константин',
    surname: 'Долоз',
    patronymic: 'Сергеевич',
    avatar: 'https://e.mospolytech.ru/old/img/photos/upc_7bc77ac8c0be13a9d8d1c5ee94cb3fd2_1685828492.jpg',
    birthday: '31.07.2001',
    sex: 'Male',
    code: 'ИПИТ-19-0075',
    faculty: 'Институт принтмедиа и информационных технологий',
    group: '191-722',
    specialty: '09.03.02 Информационные системы и технологии',
    specialization: 'Информационные и автоматизированные системы обработки информации и управления',
    degreeLength: 'Годы 1',
    educationForm: 'Очная',
    finance: 'Бюджетная',
    degreeLevel: 'Бакалавриат',
    enterYear: '2019/2020',
    orders: [
        'Приказ № 3796-УД от 24 августа 2023 г. - «Зачисление в вуз»',
        'Приказ № 3362-УД от 27 июля 2023 г. - «О завершении обучения»',
        'Приказ № 3798-УД от 30 августа 2022 г. - «О переводе на следующий курс (ликвидация задолженностей)»',
        'Приказ № 3252-УД от 24 августа 2021 г. - «О переводе на следующий курс (ликвидация задолженностей)»',
        'Приказ № 695-с от 10 сентября 2020 г. - «Об изменении учебной группы»',
        'Приказ № 640-с от 26 августа 2020 г. - «О переводе на следующий курс (ликвидация задолженностей)»',
        'Приказ № 873-с от 10 сентября 2019 г. - «О распределении по учебным группам»',
        'Приказ № 585-ОД от 3 августа 2019 г. - «О зачислении»',
    ],
    email: 'takeonfaith6@gmail.com',
    phone: '+7 (988) 500-10-77',
    accounts: [
        {
            user_status: 'stud',
            fio: 'Тестов Тест Тестович',
            status: 'Учится',
            group: 'Тестовая',
            course: '1',
            educationForm: 'Очная',
            finance: 'Бюджетное',
            degreeLevel: 'Магистр',
            token: 'IcZHdehOX5fG0URk1guJJofXaZOp%2B%2FveYriemLPFp3mcNRg5bDZtGcLkEY7%2FFGRfNqudG5H1PcbsCeVFY70a8elXOkyaxEmg4un5qP5P1Gxq4%2FWqLwaKArc11h%2F8ntRMjla3EL3oYvOWvDJqbEZKmx8BvEkIxnGjPlAHBwSG3L4%3D',
            jwt: '',
            jwt_refresh: '',
        },
        {
            fio: 'Хуснулина Дария Рашитовна',
            user_status: 'staff',
            work_place:
                'Кафедра "Информатика и информационные технологии", Старший преподаватель (Основное место работы), 1 ст., статус: Работает',
            token: '0rFgzqSaoj5KSdhk0BD%2BmAa%2F2iT272ElZ2jL2x3gLa%2BcNRg5bDZtGcLkEY7%2FFGRfNqudG5H1PcbsCeVFY70a8elXOkyaxEmg4un5qP5P1Gxq4%2FWqLwaKArc11h%2F8ntRMjla3EL3oYvOWvDJqbEZKmx8BvEkIxnGjPlAHBwSG3L4%3D',
            jwt: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJJbmRpdmlkdWFsR3VpZCI6IjkwN2FmZDliLWQ5YzUtMTFlNy05NDBhLWI0YjUyZjVmNTM0OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJ1c2VyIiwic3RhZmYiXSwibmJmIjoxNjkzMjI1ODU3LCJleHAiOjE2OTMyNjkwNTcsImlzcyI6Imh1bWFucmVzb3VyY2VzZGVwYXJ0bWVudGFwaS5tb3Nwb2x5dGVjaC5ydSIsImF1ZCI6Ikh1bWFuUmVzb3VyY2VzRGVwYXJ0bWVudCJ9.M9Nw5GRIBT70ONrY9gVFeTNLgv4WToJtrUuC3KLCTl_V8nLE2mIaDzsqBl1ydkiltgv7NJhgKTi-SQo3u6-NhWW8SQJeuqVQb6XXkVC7BfApsiwP8BA4OoIsWGCKvWTh2AYfNZLJz5h95wz1tHtVg7KbhY6pU84At09Nfps7qmA',
            jwt_refresh:
                'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJJbmRpdmlkdWFsR3VpZCI6IjkwN2FmZDliLWQ5YzUtMTFlNy05NDBhLWI0YjUyZjVmNTM0OSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJ1c2VyIiwic3RhZmYiXSwibmJmIjoxNjkzMjI1ODU3LCJleHAiOjE2OTM4MzA2NTcsImlzcyI6Imh1bWFucmVzb3VyY2VzZGVwYXJ0bWVudGFwaS5tb3Nwb2x5dGVjaC5ydSIsImF1ZCI6Ikh1bWFuUmVzb3VyY2VzRGVwYXJ0bWVudCJ9.NKIXC3z7oC-Uo4unmJhC2aivTLNs4sqSVx_i1w4msofL13qtbJSEuN7ntzJafCbluV0vHyGDG6pdLD4YGyaOVMME9H-VefIyB3cpelpU-TGphM6gHIWE1g5AO5a9I2P75qYTflqxh95rkZrBI6lKteuLwxrDHyrnwETxF9vh7R4',
        },
        {
            fio: 'Тестовый Сотрудник Тестович',
            user_status: 'staff',
            work_place: '',
            token: 'MT02r98t3%2Bt2OcPMCMwPRKFN%2F%2BGrByKftQl3Ju0cd5qcNRg5bDZtGcLkEY7%2FFGRfNqudG5H1PcbsCeVFY70a8elXOkyaxEmg4un5qP5P1Gxq4%2FWqLwaKArc11h%2F8ntRMjla3EL3oYvOWvDJqbEZKmx8BvEkIxnGjPlAHBwSG3L4%3D',
            jwt: '',
            jwt_refresh: '',
        },
        {
            user_status: 'stud',
            fio: 'Тестов2 Тест2 Тестович2',
            status: 'Учится',
            group: 'Тестовая2',
            course: '3',
            educationForm: 'Очная',
            finance: 'Бюджетное',
            degreeLevel: 'Бакалавр',
            token: 'kyYMkiefkPSmjQ9F2oDvJtHf6peEmmeX3fW5YcahpQicNRg5bDZtGcLkEY7%2FFGRfNqudG5H1PcbsCeVFY70a8elXOkyaxEmg4un5qP5P1Gxq4%2FWqLwaKArc11h%2F8ntRMjla3EL3oYvOWvDJqbEZKmx8BvEkIxnGjPlAHBwSG3L4%3D',
            jwt: '',
            jwt_refresh: '',
        },
    ],
    hasAlerts: false,
    lastaccess: '2023-08-28',
}
