name: Lint
description: Run ESLint check

runs:
    using: 'composite'
    steps:
        - name: Set up Node
          uses: actions/setup-node@v3
          with:
              node-version: '18'
              cache: 'npm'
        - name: Install dependencies
          run: npm ci
          shell: bash
        - name: ESLint check
          run: npx eslint "./src/**/*.{ts,tsx}" --config .eslintrc.js
          shell: bash
