name: PR Linter and Typescript check

on:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Run Eslint Checks
              uses: './.github/actions/eslint'

    typescript:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Run TS Checks
              uses: './.github/actions/typescript'
